### PR TITLE
Ansible 2.1

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

This PR does:
- globally require Ansible 2.1

This PR does not:
- Fix deprecation warnings
  - bare variables
  - sudo -> become (#1039)
- Migrate to the [official k8s module](https://docs.ansible.com/ansible/kubernetes_module.html)
- Use new Ansible 2 features
  - [task blocks](https://docs.ansible.com/ansible/playbooks_blocks.html)
  - [execution strategies](http://docs.ansible.com/ansible/playbooks_strategies.html)

all of which I think we should break out into separate issues and tackle one by one.

I haven't been able to test this due to #1699.

### CODE REVIEW

**Comment by siddharthist** [comment]
[CI build is failing](https://travis-ci.org/CiscoCloud/mantl/jobs/146066657#L4114) with:
```
msg: Your version of Ansible doesn't match the required version. Please install ansible-playbook with `pip install -r requirements.txt`.
```
But [it correctly installs Ansible 2.1](https://travis-ci.org/CiscoCloud/mantl/jobs/146066657#L220):
```
Collecting ansible<2.2,>=2.1 (from -r requirements.txt (line 2))
  Downloading ansible-2.1.0.0.tar.gz (1.9MB)
    100% |████████████████████████████████| 1.9MB 267kB/s 
```
(here's the [final output](https://travis-ci.org/CiscoCloud/mantl/jobs/146066657#L295) as well):
```
Successfully installed MarkupSafe-0.23 PyYAML-3.11 Pygments-2.1.3 Sphinx-1.2.3 alabaster-0.6.3 ansible-2.1.0.0 ansible-lint-3.2.0 cffi-1.7.0 cryptography-1.4 docutils-0.12 enum34-1.1.6 idna-2.1 ipaddress-1.0.16 jinja2-2.8 paramiko-2.0.1 pyasn1-0.1.9 pycparser-2.14 pycrypto-2.6.1 pytest-2.7.1
```
Anyone see where my logic is broken?

**Comment by sehqlr** [comment]
The install step that happens inside of the travis build environment is not the same as the one used in the docker container where all the testing code is currently run. That's why it's not working as expected. TBQH, it's extra complexity for little benefit, and I'm cooking up something to fix it in a PR soon.

**Comment by siddharthist** [comment]
@sehqlr Great. Please update me when that fix is in master and this is mergeable.

**Comment by siddharthist** [comment]
The CI build should be fixed. Waiting on the most recent one for confirmation.

**Comment by siddharthist** [comment]
Two CI failures that I've never seen before, they might be related:
 * https://travis-ci.org/CiscoCloud/mantl/jobs/148006270
 * https://travis-ci.org/CiscoCloud/mantl/jobs/148006258

**Comment by sehqlr** [comment]
Yeah, those are odd, but what’s the likelihood that they are directly related to the ansible upgrade?

**Comment by siddharthist** [comment]
@sehqlr We should test manually

**Comment by sehqlr** [comment]
I ran tests with this, and I get stuck on disabling firewalld. Did you ever run into that?

**Comment by tphummel** [comment]
we've had success with ansible 2.1.1.0 on AWS. we needed to remove the firewalld task as mentioned above. https://github.com/CiscoCloud/mantl/commit/344f92551dd629ed8217a7521bd329d036eb3560

**Pull request merged**
