### PR TITLE
Feature/traefik k8s ingress

### PR DESCRIPTION
**Pull request by Theaxiom**
Hi, thank you for your contribution to Mantl! Before we can accept any code into
master, we need it to meet the following criteria. If there are any you can't
satisfy yourself, go ahead and open the pull request anyway and we'll help you
test. Feel free to delete this message once you're done. Thanks again!

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by kingdonb** [comment]
I see private and public certs in here that appear to have been generated already.  Are they meant to be part of the pull request?  That seems likely to be an error to me.

The merge robot says there are conflicts, so I think this branch needs to be at least rebased onto master so it can merge cleanly.

@Dacode45 @Theaxiom 

I am new to mantl and don't have reviewer permissions yet, but I do have some kube experience.

**Comment by kingdonb** [comment]
I am going to look at this, I know a lot of these words...

Looks like your CI build is stopped because of a dependency on S3 key that is broke

Why should GCE and DO builds depend on an S3 key?

**Comment by kingdonb** [comment]
https://travis-ci.org/mantl/mantl/builds

Don't let it stop you from merging any features I guess!

**Comment by kingdonb** [comment]
Ah, I see now, this is mega-merge day.  Great!

I'll see if I can deploy it and get Traefik working myself

**Comment by kingdonb** [comment]
OK, Have reviewed v1.3.0 and it looks like Traefik was already enabled for Marathon.  This patch probably enables Traefik for Kubernetes, guessing based on the name of the PR.

**Comment by thomasvincent** [comment]
I believe I may have let a change slip in where TF state may have been kept remotely which is the S3 bucket probably. It was mega merge, lets break everything and fix it day. We had a semi stable build in 1.3 so this was the next step.

**Pull request merged**
