### PR TITLE
Adjusted to item for quoting and relative path

### PR DESCRIPTION
**Pull request by lowwalker**
There seems to be a present issue in ansible 2.x that causes the relative path to not be correct. There are multiple open issues, but I could not find the exact example. If you use Ansible 2.1 though you will see this type of error with the original stacked jinja filter -

```
TASK [kubernetes : generate kubelet systemd unit] ******************************
fatal: [mi-kubeworker-03]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/Users/ltislow/repos/mantl/kubelet-node.service.j2\\n'"}
fatal: [mi-kubeworker-01]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/Users/ltislow/repos/mantl/kubelet-node.service.j2\\n'"}
fatal: [mi-kubeworker-02]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/Users/ltislow/repos/mantl/kubelet-node.service.j2\\n'"}
```

### CODE REVIEW

**Comment by siddharthist** [comment]
@lowwalker Thanks for the PR! We currently require Ansible <2.0, but we're going to switch very soon now, so this is a great first step.

**Comment by siddharthist** [comment]
@lowwalker Looks like this branch has some merge conflicts, could you sort that out?

**Comment by lowwalker** [comment]
@siddharthist The fails in the logs don't appear to be related to my actual commit, looks like it's failing due to credentials to even get a cluster up.

**Comment by siddharthist** [comment]
@lowwalker Sorry, our CI build isn't skipping builds for forks like it should (#1760). Don't worry about it, though!

**Pull request closed without merging**
