### PR TITLE
Rebasing feature/k8-ui

### PR DESCRIPTION
**Pull request by Theaxiom**
Hi, thank you for your contribution to Mantl! Before we can accept any code into
master, we need it to meet the following criteria. If there are any you can't
satisfy yourself, go ahead and open the pull request anyway and we'll help you
test. Feel free to delete this message once you're done. Thanks again!

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by Theaxiom** [comment]
FYI: I just finished this rebase, I am playing with it to see if it resolves any of the issues. Anyone else is more than welcome to join in. 👍

**Comment by Theaxiom** [comment]
This branch uses the k8 directly from Google, no modified/forked version of k8.

**Comment by Theaxiom** [comment]
Looks like a good portion of the flannel role is missing.

**Comment by Theaxiom** [comment]
I found the rest of it here: https://github.com/mantl/kubernetes-ansible/tree/master/roles/flannel

**Comment by KaGeN101** [comment]
Grabbing this now will revert

**Comment by Theaxiom** [comment]
I pushed up the missing flannel tasks to the branch.

**Comment by Theaxiom** [comment]
We need to modify this branch for Calico support as opposed to Flannel, also keep in mind, this branch might be a red herring.

**Comment by Theaxiom** [comment]
If you want to see what this branch currently changes, you can do so here: https://github.com/mantl/mantl/pull/1912/files

**Comment by KaGeN101** [comment]
Deploying it now to check it out

**Comment by Theaxiom** [comment]
Okay, if you find anything missing, you can likely find it here: https://github.com/mantl/kubernetes-packaging

**Pull request merged**
