### PR TITLE
Remove obsoleted consul_dns_domain ansible var

### PR DESCRIPTION
**Pull request by dpavlos**
Current master is failing with the error below:
```
TASK: [vault | configure vault] *********************************************** 
fatal: [control-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dns_domain' is undefined", 'failed': True}
fatal: [control-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dns_domain' is undefined", 'failed': True}
```

Since mantl 1.2 the `consul_dns_domain` ansible var is no longer in use (https://github.com/mantl/mantl/pull/1449).

### CODE REVIEW

**Comment by Theaxiom** [comment]
Holy moly, what kind of testing do we have on this branch?

**Comment by dpavlos** [comment]
@Theaxiom This PR was opened before the creation of `integ` branch so I should probably re-open it there. Also it was totally clean from other commits and comments. I am closing it and will open a new one.

**Comment by KaGeN101** [comment]
This issue is back. Latest fix/master2 branch Pr has a fix in for thsi again or it must be propgated out competelty but as it stands currently on master the dependecy is still there

**Comment by KaGeN101** [comment]
Okay havent made a PR for fix/master2 yet please advise how this should be fixed? Curretly added varaible back in vault defaults :/

**Comment by dpavlos** [comment]
@KaGeN101 I am thinking of opening a new PR against `integ` branch. You can pick the changes from there I guess.

**Comment by KaGeN101** [comment]
Isnt it too late for integ branch now since all the PR's have already been applied to master? Better just to keer CI on there now since it is already not stable

**Comment by thomasvincent** [comment]
Make the PR's against the int branch. Right now we have master at 1.3 and stable.

**Comment by KaGeN101** [comment]
Okay sweet saw master got reverted and integ is there will use that :)

**Pull request closed without merging**
