### PR TITLE
Fix rendering of Community Supported links

### PR DESCRIPTION
**Pull request by kingdonb**
I just changed the spacing to match the toctree above that did render correctly

### CODE REVIEW

**Comment by kingdonb** [comment]
I am testing out the build using Vagrant instructions.  I added a commit to ansible role also because otherwise I got:

```
TASK: [common | restart journald service] *************************************
failed: [control-01] => {"failed": true}
msg: Failed to reload systemd-journald.service: Job type reload is not applicable for unit systemd-journald.service.

failed: [kubeworker-001] => {"failed": true}
msg: Failed to reload systemd-journald.service: Job type reload is not applicable for unit systemd-journald.service.

failed: [worker-001] => {"failed": true}
msg: Failed to reload systemd-journald.service: Job type reload is not applicable for unit systemd-journald.service.

failed: [edge-001] => {"failed": true}
msg: Failed to reload systemd-journald.service: Job type reload is not applicable for unit systemd-journald.service.
```

**Comment by kingdonb** [comment]
I got this far:

```
TASK: [vault | authenticate with vault] ***************************************
failed: [control-01] => {"changed": true, "cmd": ["vault", "auth", "-tls-skip-verify", "3746deec-d5b1-7c6e-bebd-8a6360c6c149"], "delta": "0:00:00.092447", "end": "2017-04-30 16:17:39.811213", "rc": 1, "start": "2017-04-30 16:17:39.718766", "warnings": []}
stderr: Error validating token: Error making API request.

URL: GET https://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 503. Errors:

* Vault is sealed

FATAL: all hosts have already failed -- aborting
```

I had to manually add consul_dns_domain to my generated security.yml

Think I should quit there until someone who knows more can look at it, I don't know what consul is or is for, but something sealed my vault and I guess I don't have what I need in environment variables to go further.  I'm just trying to get a deploy from master so I can test #1904 Traefik ingress controller in Kubernetes.  This is actually my very first experience with Mantl.  Chance I would have better luck with consul stuff and ansible roles completing if I am using snapshot I took last night before the mega-merge commits including #1904 that all went into master tree this morning.  I will try it out.

**Comment by KaGeN101** [comment]
AWS breaking at the same places will keep merging and testing

**Comment by KaGeN101** [comment]
1.3.0 tag is stable so could focus on things from there if you like

**Comment by kingdonb** [comment]
@KaGeN101 Thank you!

**Comment by thomasvincent** [comment]
Consul is https://www.consul.io/

**Comment by thomasvincent** [comment]
Thanks for making a small focus commit. Makes reviewing a lot easier.

**Comment by Theaxiom** [comment]
Since `master` has been rebased, does this need to also be cherry-picked to `master`?

**Pull request merged**
