### PR TITLE
Add terraform openstack module for creating LB (via Neutron LBaaS).

### PR DESCRIPTION
**Pull request by pfrybar**
Create a terraform module to allow setting up a load balancer. Added sample configuration to `openstack-modules.sample.tf` showing how this can be done to load balance across the control nodes, and across the edge nodes. I left the sample code commented out, so it has to be explicitly turned on.

Note: I found a bug in the terraform-openstack provider while testing this - https://github.com/hashicorp/terraform/pull/5557. Without this fix the creation of the LB may fail (it did more often than not for me).

### CODE REVIEW

**Comment by stevendborrelli** [comment]
One thing about this, we may not need all the commented code if it is just a sample file.

Terraform also joins all the files together, so it could be a separate file. 

How about `openstack-lb.sample.tf` with no comments?

**Comment by siddharthist** [comment]
@sehqlr Could you test this?

**Comment by siddharthist** [comment]
Pinging @sehqlr @Dacode45: Do either of you have a working Openstack environment?

**Comment by sehqlr** [comment]
I haven’t tried OS for a while, but I can take a look

**Pull request merged**
