### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by thomasvincent**
#2001 - first pass at refactoring code

### CODE REVIEW

**Comment by Theaxiom** [comment]
This is going to take some time to test and review

**Comment by thomasvincent** [comment]
I created a alpha branch for this purpose. This isn't merging into master.

**Comment by thomasvincent** [comment]
But yea I purposely blew shit up.

**Comment by thomasvincent** [comment]
This doesn't need to be merged anytime soon. More of a RFC.

**Pull request closed without merging**
