### PR TITLE
Cherry picking Vault OTP configs

### PR DESCRIPTION
**Pull request by dpavlos**
Attempting to bring Vault OTP (https://github.com/mantl/mantl/pull/1165) support into `next` branch by cherry picking previous commits that have been merged into `master` and then reverted into `integ` branch. 

- [x] Cherry picked the following commit from https://github.com/mantl/mantl/pull/1165:
   * abc576ad07d519173bcb66aae133e036d47ca25e
- [x] Updated ansible syntax in `otp.yml` and `generate-otps.yml`
- [x] Use static values for ca/client certs in `generate-otps.yml`
- [x] Added `ansible_ssh_port` variable in `Vagrantfile`
- [x] Fixed failing `generate-otps.yml` due to wrong parameters in `vault ssh` command
- [x] `vault-ssh-helper` was failing due to wrong logging configuration in PAM module
- [x] Enabled tls verification for `vault-ssh-helper`

Sample output from `generate-otps.yml` playbook:
```
TASK: [print OTPs] ************************************************************ 
ok: [control-01] => (item=('172.20.10.101', '82101925-3d15-0863-c000-1adb69962685')) => {
    "changed": false, 
    "item": [
        "172.20.10.101", 
        "82101925-3d15-0863-c000-1adb69962685"
    ], 
    "msg": "vagrant@172.20.10.101: 82101925-3d15-0863-c000-1adb69962685"
}
```

Tested with:
* Vagrant 1.9.3
* Ansible 1.9.6

### CODE REVIEW

**Comment by dpavlos** [comment]
`generate-otps.yml` playbook is failing with the following error:

```
TASK: [collect OTPs] ********************************************************** 
[...]
stderr: Error fetching username: user: Current not implemented on linux/amd64
```

**Comment by dpavlos** [comment]
The PR is ready for review. Anyone interested? @thomasvincent @Theaxiom @KaGeN101 @ChrisAubuchon

**Comment by KaGeN101** [comment]
Will look into this mine also ready

**Comment by KaGeN101** [comment]
Get this error when running this branch on AWS:
TASK: [vault | authenticate with vault] *************************************** 
failed: [mantl-dev1-control-03] => {"changed": false, "cmd": ["vault", "auth", "-ca-cert=/etc/pki/CA/ca.cert", "-client-cert=/etc/pki/mantl/cert", "-client-key=/etc/pki/mantl/key", "d9aff911-3e5c-31dd-3ade-c556049db95b"], "delta": "0:00:00.055831", "end": "2017-05-07 18:36:43.350888", "rc": 1, "start": "2017-05-07 18:36:43.295057", "warnings": []}
stderr: Error validating token: Error making API request.

URL: GET https://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 400. Errors:

* permission denied

FATAL: all hosts have already failed -- aborting

**Comment by dpavlos** [comment]
@KaGeN101 Did you checkout my own branch? The changes are not merged on `next` yet.

**Comment by KaGeN101** [comment]
Yes it is on your next_valut_p1 branch. The one I am reviewing :)

**Comment by dpavlos** [comment]
Hm weird, I haven't any issues on vagrant. Could you please paste also the task before the one that is failing? There are two vault authentication tasks there and I have to understand which one throughs this error.

**Comment by KaGeN101** [comment]
TASK: [vault | register vault service in consul] ****************************** 
changed: [mantl-dev1-control-02]
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-01]

TASK: [vault | initialize vault] ********************************************** 
ok: [mantl-dev1-control-03]

TASK: [vault | extract keys] ************************************************** 
ok: [mantl-dev1-control-03]

TASK: [vault | extract root token] ******************************************** 
ok: [mantl-dev1-control-03]

TASK: [vault | create unseal script] ****************************************** 
changed: [mantl-dev1-control-02]
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-01]

TASK: [vault | update security.yml with token] ******************************** 
ok: [mantl-dev1-control-03]

NOTIFIED: [certificates | update-ca-trust] ************************************ 
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-02]
changed: [mantl-dev1-control-01]

NOTIFIED: [vault | restart vault] ********************************************* 
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-02]
changed: [mantl-dev1-control-01]

NOTIFIED: [vault | wait for vault to listen] ********************************** 
ok: [mantl-dev1-control-02]
ok: [mantl-dev1-control-03]
ok: [mantl-dev1-control-01]

TASK: [vault | authenticate with vault] *************************************** 
failed: [mantl-dev1-control-03] => {"changed": false, "cmd": ["vault", "auth", "-ca-cert=/etc/pki/CA/ca.cert", "-client-cert=/etc/pki/mantl/cert", "-client-key=/etc/pki/mantl/key", "d9aff911-3e5c-31dd-3ade-c556049db95b"], "delta": "0:00:00.055831", "end": "2017-05-07 18:36:43.350888", "rc": 1, "start": "2017-05-07 18:36:43.295057", "warnings": []}
stderr: Error validating token: Error making API request.

URL: GET https://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 400. Errors:

* permission denied

FATAL: all hosts have already failed -- aborting

**Comment by dpavlos** [comment]
Can you apply the following debug code, re-deploy and see if the vault token gets a value?
```
--- a/roles/vault/tasks/tls-auth.yml
+++ b/roles/vault/tasks/tls-auth.yml
@@ -1,4 +1,7 @@
 ---
+- debug:
+    msg: "Vault token: {{ vault_root_token }}"
+
 - name: authenticate with vault
   sudo: yes
   run_once: yes
```

**Comment by KaGeN101** [comment]
Here you go:
TASK: [vault | install vault] ************************************************* 
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-01]
changed: [mantl-dev1-control-02]

TASK: [vault | configure vault] *********************************************** 
changed: [mantl-dev1-control-01]
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-02]

TASK: [vault | enable vault] ************************************************** 
changed: [mantl-dev1-control-02]
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-01]

TASK: [vault | wait for vault port] ******************************************* 
ok: [mantl-dev1-control-03]
ok: [mantl-dev1-control-02]
ok: [mantl-dev1-control-01]

TASK: [vault | deregister vault service in consul] **************************** 
changed: [mantl-dev1-control-02]
changed: [mantl-dev1-control-01]
changed: [mantl-dev1-control-03]

TASK: [vault | register vault service in consul] ****************************** 
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-01]
changed: [mantl-dev1-control-02]

TASK: [vault | initialize vault] ********************************************** 
ok: [mantl-dev1-control-03]

TASK: [vault | extract keys] ************************************************** 
ok: [mantl-dev1-control-03]

TASK: [vault | extract root token] ******************************************** 
ok: [mantl-dev1-control-03]

TASK: [vault | create unseal script] ****************************************** 
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-02]
changed: [mantl-dev1-control-01]

TASK: [vault | update security.yml with token] ******************************** 
ok: [mantl-dev1-control-03]

NOTIFIED: [certificates | update-ca-trust] ************************************ 
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-01]
changed: [mantl-dev1-control-02]

NOTIFIED: [vault | restart vault] ********************************************* 
changed: [mantl-dev1-control-03]
changed: [mantl-dev1-control-01]
changed: [mantl-dev1-control-02]

NOTIFIED: [vault | wait for vault to listen] ********************************** 
ok: [mantl-dev1-control-03]
ok: [mantl-dev1-control-01]
ok: [mantl-dev1-control-02]

TASK: [vault | debug ] ******************************************************** 
ok: [mantl-dev1-control-03] => {
    "msg": "Vault token: d9aff911-3e5c-31dd-3ade-c556049db95b"
}
ok: [mantl-dev1-control-02] => {
    "msg": "Vault token: d9aff911-3e5c-31dd-3ade-c556049db95b"
}
ok: [mantl-dev1-control-01] => {
    "msg": "Vault token: d9aff911-3e5c-31dd-3ade-c556049db95b"
}

TASK: [vault | authenticate with vault] *************************************** 
failed: [mantl-dev1-control-03] => {"changed": false, "cmd": ["vault", "auth", "-ca-cert=/etc/pki/CA/ca.cert", "-client-cert=/etc/pki/mantl/cert", "-client-key=/etc/pki/mantl/key", "d9aff911-3e5c-31dd-3ade-c556049db95b"], "delta": "0:00:00.054631", "end": "2017-05-07 21:21:20.633269", "rc": 1, "start": "2017-05-07 21:21:20.578638", "warnings": []}
stderr: Error validating token: Error making API request.

URL: GET https://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 400. Errors:

* permission denied

FATAL: all hosts have already failed -- aborting

**Comment by KaGeN101** [comment]
Can I test this again?

**Comment by dpavlos** [comment]
Thanks @KaGeN101 ! Sure you can test it, although I haven't changed anything since then. I am trying to understand where the problem is. If you experience the same issue again try running the following command directly from the control node as root and let me know if it works:
```
# vault auth -ca-cert=/etc/pki/CA/ca.cert -client-cert=/etc/pki/mantl/cert -client-key=/etc/pki/mantl/key <put_here_the_vault_root_token>
```
Also, what version of ansible do you use and are you testing it on a fresh or existing installation?

**Comment by KaGeN101** [comment]
Okay will try again with above and revert. 
I start clean each time I switch branches. So I guess you can say fresh.
I actually start fresh after most changes are working just to make sure it actually works from a clean deploy

**Comment by Theaxiom** [comment]
This branch needs to be rebased before it can be merged.

**Comment by dpavlos** [comment]
@Theaxiom Done.

**Comment by Theaxiom** [comment]
Thanks @dpavlos I will merge it when I get home. GitHub has silly rules about accepting merge requests on phones.

**Pull request merged**
