### PR TITLE
[TRAVIS] Update TF modules for AWS & GCE

### LINKED ISSUE #1692: ci build should use terraform modules
It appears the CI build is using legacy terraform (at least for AWS and GCE). It should use the newer terraform modules to be consistent with our recommended configuration and documentation. 

Legacy:

./terraform/aws/aws.tf
./terraform/gce/gce.tf

The ./terraform/aws.sample.tf and ./terraform/gce.sample.tf show how to use the terraform modules.

### PR DESCRIPTION
**Pull request by sehqlr**
This fixes #1692 
- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
Builds are failing on AWS, GCE

**Comment by sehqlr** [comment]
I had to rebase this on master to pull in other recent changes

**Comment by sehqlr** [comment]
This actually depends on #1808, so I'm testing that one out now. Then, I'll rebase again

**Comment by siddharthist** [comment]
Looks like some unrelated commits got added to this branch

**Pull request merged**
