### PR TITLE
Calico with Mesos CNI

### PR DESCRIPTION
**Pull request by Zogg**
Use Mesos' CNI with Calico.

### CODE REVIEW

**Comment by siddharthist** [comment]
Looks like those packages are in the 1.3 repo: https://bintray.com/shippedrepos/mantl-1.3/mesos

I'll merge #1773 into this branch in order to get a valid CI build.

**Comment by siddharthist** [comment]
CI builds all fail with this message:
```
file /usr/lib/python2.7/site-packages/setuptools/py27compat.pyc from install of mesos-1.0.0-1.x86_64 conflicts with file from package python-setuptools-0.9.8-4.el7.noarch

  file /usr/lib/python2.7/site-packages/setuptools/sandbox.py from install of mesos-1.0.0-1.x86_64 conflicts with file from package python-setuptools-0.9.8-4.el7.noarch

  file /usr/lib/python2.7/site-packages/setuptools/sandbox.pyc from install of mesos-1.0.0-1.x86_64 conflicts with file from package python-setuptools-0.9.8-4.el7.noarch

  file /usr/lib/python2.7/site-packages/setuptools/site-patch.py from install of mesos-1.0.0-1.x86_64 conflicts with file from package python-setuptools-0.9.8-4.el7.noarch

  file /usr/lib/python2.7/site-packages/setuptools/site-patch.pyc from install of mesos-1.0.0-1.x86_64 conflicts with file from package python-setuptools-0.9.8-4.el7.noarch

  file /usr/lib/python2.7/site-packages/setuptools/ssl_support.py from install of mesos-1.0.0-1.x86_64 conflicts with file from package python-setuptools-0.9.8-4.el7.noarch

  file /usr/lib/python2.7/site-packages/setuptools/ssl_support.pyc from install of mesos-1.0.0-1.x86_64 conflicts with file from package python-setuptools-0.9.8-4.el7.noarch
```

**Comment by KaGeN101** [comment]
We have calico 2.1 integrated with CNI on the k8 side this should now just be enabled on mesos side or is now solved with #1963?

**Comment by KaGeN101** [comment]
We have Calico 2.1 integrated with CNI on the k8 side. This is either now solved or CNI should just be enabled on the mesos side? See #1963

**Comment by Theaxiom** [comment]
We need to test it.

**Comment by Theaxiom** [comment]
We can test it later and fix it.

**Pull request merged**
